[package]
name = "gluesql-redb4-storage"
authors = ["Édomaur"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
redb = "4.1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
futures = "0.3"
thiserror = "2.0.3"
postcard = { version = "1", features = ["alloc"] }
uuid = { version = "1.11.0", features = ["v7"] }
async-stream = "0.3.6"

[dev-dependencies]
test-suite.workspace = true
tokio = { version = "1", features = ["rt", "macros"] }

[lints]
workspace = true
